### ISSUE TITLE
Building complications

### ISSUE THREAD

**Issue by sirandreww** [gipsyh/rIC3#4]
Congratulations on winning first place 😁. I've been working on a rust library for bit level formal verification myself and am planning to make it public once the associated paper is published. I'm trying to test this repository in order to benchmark myself and I cannot seem to build it or use it for the following reasons:
1. It requires nightly rust (which is not an issue but the command provided in the `readme` does not reflect that)
2. The dependencies are git sub-modules, and some require sub-modules of their own but I'm failing to pull them due to a missing authentication issue?

**Comment by gipsyh** [comment]
Thank you! 😁

Regarding the first issue, I’ve updated the README to reflect the requirement for nightly Rust!

As for the second issue, could you provide more details on which specific repository you’re having trouble pulling?

Thank you!

**Comment by sirandreww** [comment]
```
error: failed to run custom build command for `satif-minisat v0.2.0 (/home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/minisat-rs)`

Caused by:
  process didn't exit successfully: `/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/satif-minisat-a7fba784e8859ecd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./bindings
  cargo:rerun-if-changed=./minisat
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/satif-minisat-9c72e28bab35b8ce/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/minisat-rs/./bindings" "-DCMAKE_INSTALL_PREFIX=/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/satif-minisat-9c72e28bab35b8ce/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring incomplete, errors occurred!

  --- stderr
  fatal: Unable to find current revision in submodule path 'minisat'
  CMake Error at CMakeLists.txt:14 (add_subdirectory):
    The source directory

      /home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/minisat-rs/minisat

    does not contain a CMakeLists.txt file.


  thread 'main' panicked at /home/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `cadical v0.1.0 (/home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/cadical-rs)`

Caused by:
  process didn't exit successfully: `/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/cadical-c3aad82b464bc070/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./bindings
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/cadical-5aaaf9b50c279a86/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/cadical-rs/./bindings" "-DCMAKE_INSTALL_PREFIX=/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/cadical-5aaaf9b50c279a86/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- The C compiler identification is GNU 13.2.0
  -- The CXX compiler identification is GNU 13.2.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.4s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/cadical-5aaaf9b50c279a86/out/build
  running: cd "/home/andrew/Desktop/formal_verification/other_repos/rIC3/target/debug/build/cadical-5aaaf9b50c279a86/out/build" && MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" "cmake" "--build" "." "--target" "install" "--config" "Debug"
  [ 50%] Building CXX object CMakeFiles/bindings.dir/binding.cpp.o

  --- stderr
  fatal: Unable to find current revision in submodule path 'cadical'
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  /home/andrew/Desktop/formal_verification/other_repos/rIC3/deps/cadical-rs/bindings/binding.cpp:1:10: fatal error: cadical.hpp: No such file or directory
      1 | #include "cadical.hpp"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  gmake[2]: *** [CMakeFiles/bindings.dir/build.make:76: CMakeFiles/bindings.dir/binding.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bindings.dir/all] Error 2
  gmake: *** [Makefile:136: all] Error 2
  thread 'main' panicked at /home/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Here is the output that shows how minisat and cadical are failing, this is due to the underlying repertories not being downloaded automatically. If you want to recreate this, you can remove your github credentials from the terminal, perform `git clone` once again, and then you might see that this failure occurs on building.

**Comment by gipsyh** [comment]
Because the Git submodule links were in SSH, I changed them all to HTTPS. Re-cloning should work now.

**Comment by sirandreww** [comment]
I am able to build now :pray:
